server:
  port: 8000


redis-keeper:
  cache:
    caffeine:
      specs:
        test_10s: initialCapacity=10,maximumSize=100,expireAfterWrite=PT10S
        test_10m: initialCapacity=10,maximumSize=100,expireAfterWrite=PT10M


  redis:
    datasource:
      ds1:
        host: localhost
        port: 6379
        password: yourPass
        invoke-params-print: true

    datasources:
      ds2:
        - host: localhost
          port: 6379
          database: 1
          password: yourPass
          invoke-params-print: true

        - host: localhost
          port: 6379
          database: 2
          password: yourPass
          invoke-params-print: true

        - host: localhost
          port: 6379
          database: 3
          password: yourPass
          invoke-params-print: true

      ds3:
        - host: localhost
          port: 6379
          database: 1
          password: yourPass
          invoke-params-print: true
          status: RO

        - host: localhost
          port: 6379
          database: 2
          password: yourPass
          invoke-params-print: true

        - host: localhost
          port: 6379
          database: 3
          password: yourPass
          invoke-params-print: true
          status: RO
